#!/usr/bin/env python3

import os
import glob
import pandas as pd


# PANGIA score summary for 13 target pathogens for the 3 bioprojects: PRJEB75460, PRJEB75462 & PRJEB75463

# Bioproject directories
COHORT_DIRS = {
    "PRJEB75460": "/pub60/kirsten/Projects/PRJEB75460",
    "PRJEB75462": "/pub60/kirsten/Projects/PRJEB75462",
    "PRJEB75463": "/pub60/kirsten/Projects/PRJEB75463",
}


# Expected numbers of samples in each bioproject 

COHORT_SIZES = {
    "PRJEB75460": 973,
    "PRJEB75462": 995,
    "PRJEB75463": 998
}


# Output directory

OUTPUT_DIR = (
    "/pub60/kirsten/Projects/Results1/"
    "Section_3_pathogens/pangia"
)

os.makedirs(OUTPUT_DIR, exist_ok=True)


# Searching for the 13 target pathogens

PATHOGENS = {
    "Clostridioides difficile":
        r"^Clostridioides difficile$",

    "Clostridium perfringens":
        r"^Clostridium perfringens$",

    "Escherichia coli":
        r"^Escherichia coli",

    "Campylobacter jejuni":
        r"^Campylobacter jejuni$",

    "Listeria monocytogenes":
        r"^Listeria monocytogenes$",

    "Salmonella enterica":
        r"Salmonella enterica.*Enteritidis|Salmonella.*Enteritidis",

    "Shigella sonnei":
        r"^Shigella sonnei$",

    "Yersinia enterocolitica":
        r"^Yersinia enterocolitica$",

    "Vibrio cholerae":
        r"^Vibrio cholerae$",

    "Giardia duodenalis":
        r"^Giardia duodenalis$",

    "Cryptosporidium parvum":
        r"^Cryptosporidium parvum$",

    "Cyclospora cayetanensis":
        r"^Cyclospora cayetanensis$",

    "Human adenovirus":
        r"^Human adenovirus",
}


# Store all detections in list

all_results = []


# Process each bioproject 

for cohort, cohort_dir in COHORT_DIRS.items():

    report_files = sorted(
        glob.glob(
            os.path.join(
                cohort_dir,
                "**",
                "*.report.tsv" # search for .report.tsv pangia output files 
            ),
            recursive=True
        )
    )

    print(
        f"{cohort}: found "
        f"{len(report_files)} Pangia reports" # and print the number of these found
    )


    # check sample numbers, compare detected with expected, should match up

    expected = COHORT_SIZES[cohort]

    if len(report_files) != expected:

        print(
            f"WARNING: expected {expected} reports "
            f"but found {len(report_files)}"
        )


    # Process each samples report

    for report_file in report_files:

        sample = os.path.basename( # extract sample name from file name
            report_file
        ).replace(
            ".report.tsv",
            ""
        )


        # Read PanGIA report

        try:

            df = pd.read_csv(
                report_file,
                sep="\t", # expects tab separated
                dtype=str # read as string
            )

        except Exception as e:

            print(
                f"WARNING: could not read " # print a warning if a report could not be read, skip to next sample
                f"{report_file}: {e}"
            )

            continue


        # check required columns are there, if not the sample will be skipped

        required_columns = {
            "LEVEL",
            "NAME",
            "TAXID",
            "READ_COUNT",
            "ABUNDANCE",
            "SCORE_UNIQ"
        }

        missing = (
            required_columns
            - set(df.columns)
        )

        if missing:

            print(
                f"WARNING: {sample} missing "
                f"columns: {missing}"
            )

            continue


        # SPECIES LEVEL ONLY

        df = df[
            df["LEVEL"]
            .fillna("")
            .str.lower()
            .eq("species")
        ].copy()


        # Search for the pathogens

        for pathogen, pattern in PATHOGENS.items():

            matches = df[ # identify matching species searching name column
                df["NAME"]
                .fillna("")
                .str.match(
                    pattern,
                    case=False, # not case sensitive 
                    na=False # missing names are taken as a non match
                )
            ].copy()


            # No detection , skip to next 

            if len(matches) == 0:

                continue


            # Convert read count to numeric (as it was originally read as a string)

            matches["READ_COUNT_NUM"] = (
                pd.to_numeric(
                    matches["READ_COUNT"],
                    errors="coerce"
                )
            )


            # If multiple species rows occur,
            # keep the row with the highest read count

            matches = matches.sort_values(
                "READ_COUNT_NUM",
                ascending=False
            )


            row = matches.iloc[0]


            # Extract numerical values

            score = pd.to_numeric(
                row["SCORE_UNIQ"], # unique pangia score
                errors="coerce"
            )

            read_count = pd.to_numeric(
                row["READ_COUNT"], # number of reads assigned to the pathogen
                errors="coerce"
            )

            abundance = pd.to_numeric(
                row["ABUNDANCE"], # pangia abundance value
                errors="coerce"
            )


            # Skip invalid score if cannot be converted 

            if pd.isna(score):

                continue


            # Store result, one row added for each valid pathogen detection per sample

            all_results.append({

                "Cohort":
                    cohort,

                "Sample":
                    sample,

                "Pathogen":
                    pathogen,

                "TaxID":
                    row["TAXID"],

                "Pangia_read_count":
                    read_count,

                "Pangia_abundance":
                    abundance,

                "Pangia_score":
                    score
            })


# Create long format table for detection

detections = pd.DataFrame( # list of dictionaries converted into df
    all_results
)


if detections.empty: # if no detections stop script 

    raise SystemExit(
        "ERROR: No Pangia pathogen "
        "detections were found."
    )


# Save long format table 

long_file = os.path.join(
    OUTPUT_DIR,
    "pangia_13_pathogens_scores_long.tsv"
)

detections.to_csv(
    long_file,
    sep="\t",
    index=False
)

print()
print(
    f"Saved detection table: "
    f"{long_file}"
)


# Create summary tables for each bioproject 

for cohort in COHORT_DIRS:

    print()
    print(
        f"Creating summary for {cohort}"
    )


    # Get detections for this cohort

    cohort_data = detections[
        detections["Cohort"] == cohort
    ]


    cohort_n = COHORT_SIZES[ # expected bioproject sizes
        cohort
    ]


    summary_rows = [] # list for summary df 


    # Process all 13 pathogens

    for pathogen in PATHOGENS:

        pathogen_data = cohort_data[ # select pathogen and extract detections of this within the bioproject
            cohort_data["Pathogen"] == pathogen
        ]


        scores = pathogen_data[ # extract the pangia scores, removing any missing 
            "Pangia_score"
        ].dropna()


        n_detected = len(scores) # number of pathogens detected with a valid pangia score 


        # Pathogen detected, summary stats

        if n_detected > 0:

            median_score = scores.median()

            q1 = scores.quantile(
                0.25
            )

            q3 = scores.quantile(
                0.75
            )

            maximum_score = scores.max()

            iqr = (
                f"{q1:.3f}–{q3:.3f}"
            )


        # No detections

        else:

            median_score = ""

            iqr = ""

            maximum_score = ""


        # Percentage detected

        percent_detected = (
            n_detected
            / cohort_n
            * 100
        )


        # Store summary

        summary_rows.append({

            "Pathogen":
                pathogen,

            "n_detected":
                n_detected,

            "percent_detected":
                round(
                    percent_detected,
                    1
                ),

            "Median_Pangia_score":
                (
                    round(
                        median_score,
                        3
                    )
                    if median_score != ""
                    else ""
                ),

            "IQR":
                iqr,

            "Maximum_score":
                (
                    round(
                        maximum_score,
                        3
                    )
                    if maximum_score != ""
                    else ""
                )
        })


    # Creat summary results df

    cohort_summary = pd.DataFrame(
        summary_rows # each row reporesents one of the 13 pathogens 
    )


    # Save table 

    output_file = os.path.join(
        OUTPUT_DIR,
        f"{cohort}_pangia_scores_table.tsv"
    )


    cohort_summary.to_csv(
        output_file,
        sep="\t",
        index=False
    )


# run checks 

print()
print(
    "Detection counts by cohort:"
)

print(
    detections
    .groupby("Cohort")
    .size()
)


print()
print(
    "Detection counts by pathogen:"
)

print(
    detections
    .groupby("Pathogen")
    .size()
    .sort_values(
        ascending=False
    )
)


print()
print(
    "Pangia score extraction complete."
)
